### ISSUE TITLE
Could it be possible to search by multiple tags?

### ISSUE THREAD

**Issue by ludrol** [Neshura87/Lemmy-RFC#1]
If we have `https://example.org/t/tag` then we couldn't search for example: `tag:news + tag:EU`

The lemmy inherently is different platform than mastodon and shouldn't we pass tags as URL variables?

We should plan ahead and enable search by multiple tags on lemmy. 

In the future we could implement searching by `tag1 AND tag 2` `tag1 OR tag2` `tag1 AND NOT tag2`

**Comment by ludrol** [comment]
it would enable us to implement something like https://github.com/LemmyNet/lemmy/issues/3788 in the future

**Comment by Neshura87** [comment]
Tags are all stored as separate objects so doing this will be pretty straight forward. No additional work would be needed aside from the sorting algorithm itself.

Clsoing as answered
