### ISSUE TITLE
Using separate table for instance tags

### ISSUE THREAD

**Issue by 0WN463** [Neshura87/Lemmy-RFC#2]
> A new table "tags" would be required. This new table would consist of the columns url, name, type, deleted, ìd and community_id. Additional columns for tag display style (for example background & text color) could be added later by extending this table. The community_id field should be nullable, in which case the tag should be assumed to belong to the instance. This column will be primarily used to help list all tags belonging to the instance or a communtiy for moderation purposes (Adding/Editing/Removing tags).

I think it might be better to have a separate table for instance tags vs community tags.

1. Allows us to enforce the existence of `community_id` column for community tags, so less room for mistakes
2. Allows us to give community tags and instance tags different schemas in the future if we want, _eg_ adding more fields to instance tags for more functionalities

I know this is implementation details, but just want to put it out there

**Comment by Neshura87** [comment]
Great idea, I've added the change to the RFC text and linked this issue.
