### ISSUE TITLE
Use HTTP methods for endpoints

### ISSUE THREAD

**Issue by 0WN463** [Neshura87/Lemmy-RFC#3]
The following endpoints are suggested in the RFC.

```
/tags
/tags/create
/tags/edit
/tags/delete 
```

But actually we can just leverage on the HTTP method to perform all these using the same endpoint, to follow REST convention.

```
GET /tags
POST /tags
PUT /tags
DELETE /tags
```

I'm not entirely sure how Lemmy API's are laid out, but a preliminary check does indicate that we are using REST conventions to handle these API's.

**Comment by Neshura87** [comment]
Lemmy API is laid out as follows:

`GET /post/list` for a list of posts
`GET /post` for a single
`POST /post` to create a post
`PUT /post` to edit a post
`POST /post/delete` to delete a post

I've changed the RFC to reflect that schema
